project:
  type: website
  output-dir: docs

website:
  title: "Armenia CCDR"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Background notes"
        contents: bg-notes/*
      - section: "Supporting materials"
        contents: supporting-materials/*

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

