---
title: "Poverty Dashboards"
author: "Renato Vargas"
format: dashboard
---

```{r}
#| warning: FALSE
#| message: FALSE
#| output: FALSE
#| lst-label: lst-load-packages

# Clean workspace
rm(list = ls())

# Armenia country ISO code
iso <- "ARM"

# Survey year
surveyyear <- 2022

# Exchange rate USD per dram
er <- 0.002310

library(tidyverse) # includes dplyr, ggplot2 and others
library(haven)     # to read SPSS and Stata datasets
library(readxl)    # to read from MS-Excel
library(openxlsx)  # to write to MS-Excel.
library(gt)        # pretty tables
library(car)       # companion to applied regression
library(modelr)    # regression models
#library(anesrake)  
# Raking reweighting but we don't load it, because 
# it changes the meaning of summarize from dplyr, 
# so we use the form anesrake::anesrake() when using it.
#library(ebal)      # Entropy reweighting (not used)
library(janitor)   # pretty subtotals
library(broom)     # More regressions
library(purrr)     # map vectors (aggregation)
library(zoo)       # Calculate moving window average and max value

# Geopackages
library(sf)        # to read and write shapefile maps
library(terra)     # to perform geocalculations
library(tmap)  

# Load data
load("outputs/microsimulation.RData")

```

## Row {height="40%"}

```{r}
#| title: Poverty results

new_poor_scenarios %>% 
  gt(rowname_col = "NAM_1") %>% 
  cols_label(
    total_population = md("Total"),
    poor_baseline = md("Baseline"),
    poor_dry_hot = md("Dry/Hot"),
    poor_nzs = md("NZS"),
    new_p_lab_cc = md("CC"),
    new_p_lab_cc_foodPI = md("BL + Food P."),
    new_p_dry_hot_food2 = md("D/H + Food P."),
    new_p_baseline_energy = md("BL + Energy P."),
    new_p_nzs_energy = md("NZS + Energy P."),
    new_p_EM_baseline_energy = md("BL + EModel P."),
    new_p_EM_nzs_energy = md("NZS + EModel P.")
  ) %>% 
  fmt_number(columns = everything(),
             decimals = 0)

```



## Row {height="60%"}
### Column

```{r}
#| title: Changes to the distribution from macro scenarios
#| padding: 0px
#| warning: FALSE
#| message: FALSE
#| lst-label: lst-scenario-distribution-plots
#| lst-cap: "Plotting equivalized consumption per capita distribution by scenario"
#| label: fig-scenario-distribution-plots
#| fig-cap: "Equivalized consumption per capita distribution by scenario"

# Basic density plot comparing equivalized consumption per capita
ggplot(ca_microsim) +
  geom_density(
    data = ca_microsim,
    aes(x = aec_r_2022, fill = 'Baseline 2022'),
    alpha = 0.4) +
  geom_density(
    data = ca_microsim,
    aes(x = aec_r_2030_nzs, fill = 'NZS 2030'),
    alpha = 0.4) +
  geom_density(
    data = ca_microsim,
    aes(x = aec_r_2030_dry_hot, fill = 'Dry/Hot 2030'),
    alpha = 0.4) +
  geom_density(
    data = ca_microsim,
    aes(x = aec_r_2030_baseline, fill = 'Baseline 2030'),
    alpha = 0.4) +
  labs(
    fill = "Scenario Variant",
    # title = "Comparison of Consumption Distributions",
    x = "Equivalized consumption (Dram)",
    y = "Probability") +
  theme_minimal()+
  coord_cartesian(xlim = c(0, 500000),
          #        ylim = c(0.000005,0.0000160)
                  ) + # Zoom in without removing data
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(labels = scales::comma)+
  geom_vline(xintercept = 55883,
             color = "red",
             linetype = "dotted",
             linewidth =0.8) +
  annotate("text",
           x = 55883,
           y = 0.0000025,
           #label = "Poverty line\nAMD 55,883",
           label = "Poverty line",
           color = "black",
           hjust = -0.1,
           # vjust = -3.5,
           #angle = 90,
           size = 3)
```

### Column {.tabset}

```{r}
#| title: Direct CC
#| padding: 0px
tm_shape(new_poor_map)+
  tm_polygons("new_p_lab_cc_pct", title="Percent", legend.show = TRUE) +
  tm_text(c("new_p_lab_cc_label"), size = .7, col = "black")+
  tm_layout(legend.position = c("right", "top"),
            #legend.outside = TRUE,
            title= "New poor as a percentage of Marz population\nDirect CC",
            title.position = c('left', 'bottom'),
            title.size = 0.9,
            asp = 1)

```

```{r}
#| title: Direct CC + Food Price
#| padding: 0px
tm_shape(new_poor_map)+
  tm_polygons("new_poor_lab_cc_foodPI_pct",
              title="Percent", 
              legend.show = TRUE) +
  tm_text(c("new_p_lab_cc_foodPI_label"), size = .7, col = "black")+
  tm_layout(legend.position = c("right", "top"), 
            title= "New poor as a percentage of Marz population\nDirect CC + Food Price",
            title.position = c('left', 'bottom'),
            title.size = 0.9,
            asp=1)
```

```{r}
#| title: Baseline + Energy Price
#| padding: 0px
tm_shape(new_poor_map)+
  tm_polygons("new_poor_baseline_energy_pct",
              title="Percent", 
              legend.show = TRUE) +
  tm_text(c("new_p_b_energy_label"), size = .7, col = "black")+
  tm_layout(legend.position = c("right", "top"), 
            title= "New poor as a percentage of Marz population\nBaseline + Energy Price",
            # outer.margins=c(.10,.10, .10, .10), 
            title.position = c('left', 'bottom'),
            title.size = 0.9,
            asp = 1)

```

```{r}
#| title: NZS + Energy Price
#| padding: 0px
tm_shape(new_poor_map)+
  tm_polygons("new_poor_nzs_energy_pct",
              title="Percent", 
              legend.show = TRUE) +
  tm_text(c("new_p_nzs_energy_label"), size = .7, col = "black")+
  tm_layout(legend.position = c("right", "top"), 
            title= "New poor as a percentage of Marz population\nNZS + Energy Price",
            #outer.margins=c(.10,.10, .10, .10), 
            title.position = c('left', 'bottom'),
            title.size = 0.9,
            asp = 1)

```

